/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.12
 * Generated at: 2024-02-20 04:32:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.time.LocalDateTime;

public final class custom_002dtag_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/custom-tag.tld", Long.valueOf(1708403439691L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.time.LocalDateTime");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Custom Tag</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <h1> ");
      if (_jspx_meth_custom_005fprint_005f0(_jspx_page_context))
        return;
      out.write("</h1>\r\n");
      out.write("  <h1> ");
      if (_jspx_meth_custom_005fprint_005f1(_jspx_page_context))
        return;
      out.write("</h1>\r\n");
      out.write("  <h1> ");
      if (_jspx_meth_custom_005fprint_005f2(_jspx_page_context))
        return;
      out.write("</h1>\r\n");
      out.write("  <h1> ");
      if (_jspx_meth_custom_005fprint_005f3(_jspx_page_context))
        return;
      out.write("</h1>\r\n");
      out.write("  \r\n");
      out.write(" <h1> LocalDate : ");
      if (_jspx_meth_custom_005fdatetime_005f0(_jspx_page_context))
        return;
      out.write(" </h1>\r\n");
      out.write(" <h1> LocalTime : ");
      if (_jspx_meth_custom_005fdatetime_005f1(_jspx_page_context))
        return;
      out.write(" </h1>\r\n");
      out.write(" <h1> LocalDateTime : ");
      if (_jspx_meth_custom_005fdatetime_005f2(_jspx_page_context))
        return;
      out.write(" </h1>\r\n");
      out.write(" <h1> Invalid : ");
      if (_jspx_meth_custom_005fdatetime_005f3(_jspx_page_context))
        return;
      out.write(" </h1>\r\n");
      out.write(" <h1> Blank : ");
      if (_jspx_meth_custom_005fdatetime_005f4(_jspx_page_context))
        return;
      out.write(" </h1>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_custom_005fprint_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  custom:print
    tag.PrintTag _jspx_th_custom_005fprint_005f0 = new tag.PrintTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_custom_005fprint_005f0);
    try {
      _jspx_th_custom_005fprint_005f0.setJspContext(_jspx_page_context);
      _jspx_th_custom_005fprint_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_custom_005fprint_005f0, null));
      _jspx_th_custom_005fprint_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_custom_005fprint_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_custom_005fprint_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  custom:print
    tag.PrintTag _jspx_th_custom_005fprint_005f1 = new tag.PrintTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_custom_005fprint_005f1);
    try {
      _jspx_th_custom_005fprint_005f1.setJspContext(_jspx_page_context);
      _jspx_th_custom_005fprint_005f1.setJspBody(new Helper( 1, _jspx_page_context, _jspx_th_custom_005fprint_005f1, null));
      _jspx_th_custom_005fprint_005f1.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_custom_005fprint_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_custom_005fprint_005f2(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  custom:print
    tag.PrintTag _jspx_th_custom_005fprint_005f2 = new tag.PrintTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_custom_005fprint_005f2);
    try {
      _jspx_th_custom_005fprint_005f2.setJspContext(_jspx_page_context);
      _jspx_th_custom_005fprint_005f2.setJspBody(new Helper( 2, _jspx_page_context, _jspx_th_custom_005fprint_005f2, null));
      _jspx_th_custom_005fprint_005f2.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_custom_005fprint_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_custom_005fprint_005f3(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  custom:print
    tag.PrintTag _jspx_th_custom_005fprint_005f3 = new tag.PrintTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_custom_005fprint_005f3);
    try {
      _jspx_th_custom_005fprint_005f3.setJspContext(_jspx_page_context);
      _jspx_th_custom_005fprint_005f3.setJspBody(new Helper( 3, _jspx_page_context, _jspx_th_custom_005fprint_005f3, null));
      _jspx_th_custom_005fprint_005f3.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_custom_005fprint_005f3);
    }
    return false;
  }

  private boolean _jspx_meth_custom_005fdatetime_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  custom:datetime
    tag.DateTimeTag _jspx_th_custom_005fdatetime_005f0 = new tag.DateTimeTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_custom_005fdatetime_005f0);
    try {
      _jspx_th_custom_005fdatetime_005f0.setJspContext(_jspx_page_context);
      // /custom-tag.jsp(18,18) name = type type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_custom_005fdatetime_005f0.setType("date");
      _jspx_th_custom_005fdatetime_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_custom_005fdatetime_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_custom_005fdatetime_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  custom:datetime
    tag.DateTimeTag _jspx_th_custom_005fdatetime_005f1 = new tag.DateTimeTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_custom_005fdatetime_005f1);
    try {
      _jspx_th_custom_005fdatetime_005f1.setJspContext(_jspx_page_context);
      // /custom-tag.jsp(19,18) name = type type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_custom_005fdatetime_005f1.setType("time");
      _jspx_th_custom_005fdatetime_005f1.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_custom_005fdatetime_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_custom_005fdatetime_005f2(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  custom:datetime
    tag.DateTimeTag _jspx_th_custom_005fdatetime_005f2 = new tag.DateTimeTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_custom_005fdatetime_005f2);
    try {
      _jspx_th_custom_005fdatetime_005f2.setJspContext(_jspx_page_context);
      // /custom-tag.jsp(20,22) name = type type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_custom_005fdatetime_005f2.setType("datetime");
      _jspx_th_custom_005fdatetime_005f2.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_custom_005fdatetime_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_custom_005fdatetime_005f3(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  custom:datetime
    tag.DateTimeTag _jspx_th_custom_005fdatetime_005f3 = new tag.DateTimeTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_custom_005fdatetime_005f3);
    try {
      _jspx_th_custom_005fdatetime_005f3.setJspContext(_jspx_page_context);
      // /custom-tag.jsp(21,16) name = type type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_custom_005fdatetime_005f3.setType("abc");
      _jspx_th_custom_005fdatetime_005f3.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_custom_005fdatetime_005f3);
    }
    return false;
  }

  private boolean _jspx_meth_custom_005fdatetime_005f4(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  custom:datetime
    tag.DateTimeTag _jspx_th_custom_005fdatetime_005f4 = new tag.DateTimeTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_custom_005fdatetime_005f4);
    try {
      _jspx_th_custom_005fdatetime_005f4.setJspContext(_jspx_page_context);
      // /custom-tag.jsp(22,14) name = type type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_custom_005fdatetime_005f4.setType("");
      _jspx_th_custom_005fdatetime_005f4.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_custom_005fdatetime_005f4);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private jakarta.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, jakarta.servlet.jsp.JspContext jspContext, jakarta.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write(" This is content one");
      return false;
    }
    public boolean invoke1( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write(" This is content two");
      return false;
    }
    public boolean invoke2( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write(" This is content three");
      return false;
    }
    public boolean invoke3( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write(" This is content four");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws jakarta.servlet.jsp.JspException
    {
      jakarta.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(jakarta.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
          case 2:
            invoke2( out );
            break;
          case 3:
            invoke3( out );
            break;
        }
        jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof jakarta.servlet.jsp.SkipPageException)
            throw (jakarta.servlet.jsp.SkipPageException) e;
        throw new jakarta.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
